---
apiVersion: v2
name: owncloud
version: 0.0.0-devel
description: ownCloud Server Helm chart
appVersion: 10.11.0
home: https://owncloud.com/
keywords:
  - owncloud
  - files
  - collaboration
  - sharing
maintainers:
  - name: ownCloud GmbH
    email: devops@owncloud.com
    url: https://owncloud.com
type: application
kubeVersion: "~1.21.0 || ~1.22.0 || ~1.23.0 || ~1.24.0 || ~1.25.0" # if this changes, also kubernetesVersions in .drone.star needs to be changed
sources:
  - https://github.com/owncloud-docker/helm-charts
  - https://github.com/owncloud-docker/server
  - https://github.com/owncloud/core
dependencies:
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mariadb
    version: 11.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
